CREATE TABLE users(
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    enable BOOLEAN DEFAULT TRUE NOT NULL
);